/* cv-demo.js — interactive + animated ferrocene voltammogram (Plotly)
   Centerpiece of Act 3. A marker sweeps in time, drawing the i–E loop,
   synced to a triangular E(t) inset — teaching what a CV actually is.
   Data: window.CV_DATA (generated by analyze_cv.py, shipped as data/cv_data.js). */
(function () {
  const FONT = { family: "Inter, system-ui, sans-serif", color: "#93a4bd", size: 13 };
  const GRID = "rgba(148,163,184,0.12)";
  const state = { built: false, playing: false, k: 0, raf: null };

  function baseLayout(xt, yt) {
    return {
      paper_bgcolor: "rgba(0,0,0,0)", plot_bgcolor: "rgba(8,12,22,0.6)",
      font: FONT, margin: { l: 58, r: 16, t: 10, b: 46 },
      xaxis: { title: xt, gridcolor: GRID, zerolinecolor: GRID, color: "#93a4bd" },
      yaxis: { title: yt, gridcolor: GRID, zeroline: true, zerolinecolor: "rgba(148,163,184,0.35)", color: "#93a4bd" },
      showlegend: false, hovermode: "closest"
    };
  }
  const CONFIG = { responsive: true, displaylogo: false,
    modeBarButtonsToRemove: ["lasso2d", "select2d", "toggleSpikelines"] };

  function build() {
    const D = window.CV_DATA;
    if (!D || !document.getElementById("cvplot")) return;
    const c = D.cycle, p = D.peaks, m = D.metrics;
    const rising = c.rising;
    // split ghost into forward (rising) / reverse (falling) so the two halves read
    const fE = [], fi = [], rE = [], ri = [];
    for (let n = 0; n < c.E.length; n++) {
      if (rising[n]) { fE.push(c.E[n]); fi.push(c.i[n]); }
      else { rE.push(c.E[n]); ri.push(c.i[n]); }
    }

    // ---- main i–E plot ----
    Plotly.newPlot("cvplot", [
      { x: fE, y: fi, mode: "lines", name: "forward",
        line: { color: "rgba(56,189,248,0.22)", width: 2 }, hoverinfo: "skip" },
      { x: rE, y: ri, mode: "lines", name: "reverse",
        line: { color: "rgba(244,114,182,0.22)", width: 2 }, hoverinfo: "skip" },
      { x: [], y: [], mode: "lines", name: "sweep",          // progress (extendTraces)
        line: { color: "#e8eef7", width: 3 },
        hovertemplate: "E = %{x:.3f} V<br>i = %{y:.3f} mA/cm²<extra></extra>" },
      { x: [c.E[0]], y: [c.i[0]], mode: "markers", name: "now",
        marker: { color: "#38bdf8", size: 14, line: { color: "#fff", width: 1.5 } },
        hoverinfo: "skip" },
      { x: [p.Epa, p.Epc], y: [p.ipa, p.ipc], mode: "markers+text",
        text: ["  E<sub>pa</sub>", "  E<sub>pc</sub>"], textposition: "middle right",
        textfont: { color: "#cbd5e1", size: 13 },
        marker: { color: ["#f472b6", "#a3e635"], size: 11, symbol: "circle-open",
                  line: { width: 2 } }, hoverinfo: "skip", visible: false }
    ], baseLayout("Potential  E  /  V", "Current density  /  mA cm⁻²"), CONFIG);

    // ---- E(t) inset ----
    if (document.getElementById("cvplot-et")) {
      Plotly.newPlot("cvplot-et", [
        { x: c.t, y: c.E, mode: "lines", line: { color: "rgba(148,163,184,0.3)", width: 2 }, hoverinfo: "skip" },
        { x: [], y: [], mode: "lines", line: { color: "#38bdf8", width: 2.5 }, hoverinfo: "skip" },
        { x: [c.t[0]], y: [c.E[0]], mode: "markers", marker: { color: "#38bdf8", size: 9 }, hoverinfo: "skip" }
      ], Object.assign(baseLayout("t  /  s", "E  /  V"),
         { margin: { l: 44, r: 8, t: 6, b: 34 } }), { responsive: true, displayModeBar: false, staticPlot: true });
    }
    state.built = true; state.k = 0;
    fillMetrics(m);
  }

  function fillMetrics(m) {
    const el = document.getElementById("cv-metrics");
    if (!el) return;
    const rows = [
      ["E½", m.E_half.toFixed(3) + " V"],
      ["ΔEp", m.dEp_mV + " mV"],
      ["Epa", m.Epa.toFixed(3) + " V"],
      ["Epc", m.Epc.toFixed(3) + " V"],
      ["|ipa/ipc|", m.ratio.toFixed(2)],
      ["scan rate", m.scan_rate_mVs + " mV/s"]
    ];
    el.innerHTML = rows.map(r =>
      `<div class="metric"><div class="v">${r[1]}</div><div class="k">${r[0]}</div></div>`).join("");
  }

  function step() {
    const D = window.CV_DATA, c = D.cycle;
    if (state.k >= c.E.length) { pause(); revealPeaks(); return; }
    const STEP = 4;                                  // points appended per frame
    const x = [], y = [], xt = [], yt = [];
    for (let n = 0; n < STEP && state.k < c.E.length; n++, state.k++) {
      x.push(c.E[state.k]); y.push(c.i[state.k]);
      xt.push(c.t[state.k]); yt.push(c.E[state.k]);
    }
    const k = Math.min(state.k, c.E.length - 1);
    Plotly.extendTraces("cvplot", { x: [x], y: [y] }, [2]);
    Plotly.restyle("cvplot", {
      x: [[c.E[k]]], y: [[c.i[k]]],
      "marker.color": c.rising[k] ? "#38bdf8" : "#f472b6"
    }, [3]);
    if (document.getElementById("cvplot-et")) {
      Plotly.extendTraces("cvplot-et", { x: [xt], y: [yt] }, [1]);
      Plotly.restyle("cvplot-et", { x: [[c.t[k]]], y: [[c.E[k]]] }, [2]);
    }
    state.raf = requestAnimationFrame(step);
  }

  function revealPeaks() { if (state.built) Plotly.restyle("cvplot", { visible: true }, [4]); }

  function play() {
    if (!state.built) build();
    const c = window.CV_DATA.cycle;
    if (state.k >= c.E.length) reset();
    state.playing = true; setBtn();
    state.raf = requestAnimationFrame(step);
  }
  function pause() {
    state.playing = false; if (state.raf) cancelAnimationFrame(state.raf); setBtn();
  }
  function reset() {
    if (!state.built) { build(); return; }
    pause(); state.k = 0;
    Plotly.restyle("cvplot", { x: [[]], y: [[]] }, [2]);
    Plotly.restyle("cvplot", { x: [[window.CV_DATA.cycle.E[0]]], y: [[window.CV_DATA.cycle.i[0]]] }, [3]);
    Plotly.restyle("cvplot", { visible: false }, [4]);
    if (document.getElementById("cvplot-et")) {
      Plotly.restyle("cvplot-et", { x: [[]], y: [[]] }, [1]);
      Plotly.restyle("cvplot-et", { x: [[window.CV_DATA.cycle.t[0]]], y: [[window.CV_DATA.cycle.E[0]]] }, [2]);
    }
  }
  function toggle() { state.playing ? pause() : play(); }
  function setBtn() {
    const b = document.getElementById("cv-play");
    if (b) b.textContent = state.playing ? "⏸  Pause" : "▶  Play sweep";
  }

  window.CVDemo = {
    ensure() { if (!state.built) build(); },
    play, pause, reset, toggle,
    autoplay() { this.ensure(); if (!state.playing && state.k === 0) play(); }
  };
})();
